version: '3.8'

services:
  mongodb:
    image: mongo:latest # usar a ultima versão de imagem.
    hostname: mongodb
    container_name: desafio_01
    restart: unless-stopped
    environment: # variaveis para acessar o mongo db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senha_01
    ports:
      - 27017:27017
    volumes:
      - ./database-data:/data/db  ""
  
  # Conexão com o Mongo Express
  mongo-express:
    image: mongo-express:latest # usar a ultima versão de imagem
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: senha_01
      ME_CONFIG_MONGODB_SERVER: mongodb 
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - 8081:8081
    volumes:
      - ./database-mongo:/data/db ""
